CREATE TABLE PEDIDOS
(
  ID INTEGER CONSTRAINT PEDIDOS_PK PRIMARY KEY
, NUMERO INTEGER NOT NULL
, DATA DATE
, DESCRICAO VARCHAR(20)
, VALOR NUMERIC(9,2)
);


CREATE SEQUENCE SEQ_PEDIDOS START 1;

CREATE TABLE MERCADORIAS
(
  ID INTEGER CONSTRAINT MERCADORIAS_PK PRIMARY KEY
, CODIGO VARCHAR(20) NOT NULL
);

INSERT INTO MERCADORIAS (ID, CODIGO) VALUES ('1', 'CADERNO');
INSERT INTO MERCADORIAS (ID, CODIGO) VALUES ('2', 'LIVRO');
INSERT INTO MERCADORIAS (ID, CODIGO) VALUES ('3', 'MOCHILA');

ALTER TABLE PEDIDOS ADD COLUMN ID_MERC INTEGER NOT NULL;

ALTER TABLE PEDIDOS ADD CONSTRAINT PEDIDOS_FK1 FOREIGN KEY (ID_MERC) REFERENCES MERCADORIAS (ID);