CREATE TABLE PEDIDOS
(
  ID NUMBER NOT NULL
, NUMERO NUMBER NOT NULL
, DATA DATE
, DESCRICAO VARCHAR2(20)
, VALOR NUMBER(9,2)
, CONSTRAINT PEDIDOS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);


CREATE SEQUENCE SEQ_PEDIDOS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999 MINVALUE 1 CACHE 200;

CREATE TABLE MERCADORIAS
(
  ID NUMBER NOT NULL
, CODIGO VARCHAR2(20) NOT NULL
, CONSTRAINT MERCADORIAS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

INSERT INTO "BCP"."MERCADORIAS" (ID, CODIGO) VALUES ('1', 'CADERNO');
INSERT INTO "BCP"."MERCADORIAS" (ID, CODIGO) VALUES ('2', 'LIVRO');
INSERT INTO "BCP"."MERCADORIAS" (ID, CODIGO) VALUES ('3', 'MOCHILA');

ALTER TABLE PEDIDOS
ADD (ID_MERC NUMBER NOT NULL);

ALTER TABLE PEDIDOS
ADD CONSTRAINT PEDIDOS_FK1 FOREIGN KEY
(
  ID_MERC
)
REFERENCES MERCADORIAS
(
  ID
)
ENABLE;