CREATE OR REPLACE PACKAGE BCP_PKG AS
    FUNCTION INICIAR(VALOR NUMBER) RETURN NUMBER;
    FUNCTION SOMAR(VALOR NUMBER) RETURN NUMBER;
    FUNCTION SUBTRAIR(VALOR NUMBER) RETURN NUMBER;
    FUNCTION MULTIPLICAR(VALOR NUMBER) RETURN NUMBER;
    FUNCTION DIVIDIR(VALOR NUMBER) RETURN NUMBER;
END BCP_PKG;

CREATE OR REPLACE PACKAGE BODY BCP_PKG AS
  RESULTADO NUMBER := 0;

  FUNCTION INICIAR(VALOR NUMBER) RETURN NUMBER IS
  BEGIN
    RESULTADO := VALOR;
    RETURN RESULTADO;
  END;

  FUNCTION SOMAR(VALOR NUMBER) RETURN NUMBER IS
  BEGIN
    RESULTADO := RESULTADO + VALOR;
    RETURN RESULTADO;
  END;

  FUNCTION SUBTRAIR(VALOR NUMBER) RETURN NUMBER IS
  BEGIN
    RESULTADO := RESULTADO - VALOR;
    RETURN RESULTADO;
  END;

  FUNCTION MULTIPLICAR(VALOR NUMBER) RETURN NUMBER IS
  BEGIN
    RESULTADO := RESULTADO * VALOR;
    RETURN RESULTADO;
  END;

  FUNCTION DIVIDIR(VALOR NUMBER) RETURN NUMBER IS
  BEGIN
    RESULTADO := RESULTADO / VALOR;
    RETURN RESULTADO;
  END;

END BCP_PKG;