DEFINE USER = BCP;
DEFINE PASS = "BCP";
CREATE USER &&USER PROFILE default IDENTIFIED BY "&&PASS" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT CREATE VIEW TO "&&USER";
GRANT "CONNECT" TO "&&USER";
GRANT CREATE TABLE TO "&&USER";
GRANT CREATE TYPE TO "&&USER";
GRANT CREATE SEQUENCE TO "&&USER";
GRANT CREATE PROCEDURE TO "&&USER";
GRANT SELECT ANY DICTIONARY TO "BCP";

ALTER USER "&&USER" QUOTA UNLIMITED ON "USERS";